/**
 * Created by haconglinh on 06/03/2017.
 */


export const FETCH_CHART_DATA_SUCCESS = 'FETCH_CHART_DATA_SUCCESS';
export const FETCH_CHART_DATA_ONE_DAY_SUCCESS = 'FETCH_CHART_DATA_ONE_DAY_SUCCESS';
export const FETCH_CHART_DATA_FAILURE = 'FETCH_CHART_DATA_FAILURE';


export const FETCH_TICKER_DATA_SUCCESS = 'FETCH_TICKER_DATA_SUCCESS';
export const FETCH_TICKER_DATA_FAILURE = 'FETCH_TICKER_DATA_FAILURE';


export const FETCH_PERFORMANCE_DATA_SUCCESS = 'FETCH_PERFORMANCE_DATA_SUCCESS';
export const FETCH_PERFORMANCE_DATA_FAILURE = 'FETCH_PERFORMANCE_DATA_FAILURE';


export const CHANGE_INSTRUMENT_ID = 'CHANGE_INSTRUMENT_ID';


export const CHANGE_PERIOD_BY_MEOMEO = 'CHANGE_PERIOD_BY_MEOMEO';


export const NETWORK_CHANGE = 'NETWORK_CHANGE';


export const UPDATE_DATA = 'UPDATE_DATA';
